config/routes.rb
Rails.application.routes.draw do
  root to:'public/homes#top'
  get '/about' => 'public/homes#about'

  scope module: :public do
    get 'customers/confirm' => 'customers#confirm'
    get 'customers/my_page' => 'customers#show'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :customers, only:[:update]
    get 'customers/edit' => 'customers#edit'
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :update, :destroy, :create]
    delete 'cart_items_destroy_all' => 'cart_items#destroy_all'

    get 'orders/new' => 'orders#new'
    get 'orders/:id' => 'orders#show'
    post 'orders/confirm' => 'orders#confirm'
    post 'orders' => 'orders#create'
    get 'orders_complete' => 'orders#complete'
    get 'orders' => 'orders#index'
  end
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registration: 'admin/registrations'
  }

  get '/admin' => 'admin/homes#top'
  namespace :admin do
    root to:'homes#top'
    resources :genres, only:[:index, :create, :edit, :update]
    resources :items, only:[:new, :create, :index, :show, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end




end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy



end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :emial, :postal_code, :address, :telephone_number, :is_active)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
   def destroy
     super
   end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end


end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="row">
 <h4><div class="admin-title"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</div></h4>
</div>
<div class="row">
 <div class="col-9">
  <%= form_with model:@customer, method: :patch, url: admin_customer_path, local:true do |f| %>
  <table class="table table-borderless">
   <tbody>
    <tr>
     <td>会員ID</td>
     <td><%= f.label @customer.id %></td>
    </tr>
    <tr>
     <td>氏名</td>
     <td>
      <%= f.text_field :last_name %>
      <%= f.text_field :first_name %>
     </td>
    </tr>
    <tr>
     <td>フリガナ</td>
     <td>
      <%= f.text_field :last_name_kana %>
      <%= f.text_field :first_name_kana %>
     </td>
    </tr>
    <tr>
     <td>郵便番号</td>
     <td><%= f.text_field :postal_code %></td>
    </tr>
    <tr>
     <td>住所</td>
     <td> <%= f.text_field :address %></td>
    </tr>
    <tr>
     <td>電話番号</td>
     <td><%= f.text_field :telephone_number %></td>
    </tr>
    <tr>
     <td>メールアドレス</td>
     <td><%= f.text_field :email %></td>
    </tr>
    <tr>
     <td>会員ステータス</td>
     <td>
      <%= f.radio_button :is_active, false, checked: true %>
      <%= f.label :is_active, "有効", value: false %>
      <%= f.radio_button :is_active, true %>
      <%= f.label :is_active, "退会", value: true %>
     </td>
    </tr>
   </tbody>
  </table>


  <%= f.submit"変更を保存", class:"btn btn-success w-120px ml-220px" %>
  <% end %>
 </div>
</div>

app/views/admin/customers/index.html.erb
<div class="row">
 <h4><div class="admin-title">会員一覧</div></h4>
</div>
<div class="row">
 <table class="table">
   <thead>
     <tr class="table-color">
       <th>会員ID</th>
       <th>氏名</th>
       <th>メールアドレス</th>
       <th>ステータス</th>
     </tr>
   </thead>

   <tbody>
     <% @customers.each do |customer| %>
     <tr>
       <td><%= customer.id %></td>
       <td><%= link_to admin_customer_path(customer) do %>
        <div class="text-dark">
           <ins>
            <%= customer.last_name %>
            <%= customer.first_name %>
           </ins>
        </div>
           <% end %>
       </td>
       <td><%= customer.email %></td>
       <td>
         <% if customer.is_active == true %>
         退会
         <% else %>
         <div class="text-success">有効</div>
         <% end %>
       </td>
     </tr>
     <% end %>
   </tbody>
 </table>
</div>
<div class="row">
 <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="row">
  <h4>
    <div class="admin-title">
     <%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細
    </div>
  </h4>
</div>
<div class="row">
  <div class="col-6">
  <table class="table table-borderless">
   <tbody>
     <tr>
       <td>会員ID</td>
       <td><%= @customer.id %></td>
     </tr>
     <tr>
       <td>氏名</td>
       <td>
         <%= @customer.last_name %>
         <%= @customer.first_name %>
       </td>
     </tr>
     <tr>
       <td>フリガナ</td>
       <td>
        <%= @customer.last_name_kana %>
        <%= @customer.first_name_kana %>
       </td>
     </tr>
     <tr>
       <td>郵便番号</td>
       <td><%= @customer.postal_code %></td>
     </tr>
     <tr>
      <td>住所</td>
      <td><%= @customer.address %></td>
     </tr>
     <tr>
      <td>電話番号</td>
      <td><%= @customer.telephone_number %></td>
     </tr>
     <tr>
      <td>メールアドレス</td>
      <td><%= @customer.email %></td>
     </tr>
     <tr>
      <td>会員ステータス</td>
      <td>
        <% if @customer.is_active == true %>
        無効
        <% else %>
        <strong class="text-success">有効</strong>
        <% end %>
      </td>
     </tr>
  </tbody>
 </table>
 </div>
</div>
<div class="row">
  <div class="ml-90px">
    <%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success" %>
  </div>
  <div class="ml-90px">
    <%= link_to "注文履歴一覧を見る", admin_path, class:"btn btn-primary" %>
  </div>
</div>