config/routes.rb
Rails.application.routes.draw do
  root to:'public/homes#top'
  get '/about' => 'public/homes#about'

  scope module: :public do
    get 'customers/confirm' => 'customers#confirm'
    get 'customers/my_page' => 'customers#show'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :customers, only:[:update]
    get 'customers/edit' => 'customers#edit'
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :update, :destroy, :create]
    delete 'cart_items_destroy_all' => 'cart_items#destroy_all'

    get 'orders/new' => 'orders#new'
    get 'orders/:id' => 'orders#show'
    post 'orders/confirm' => 'orders#confirm'
    post 'orders' => 'orders#create'
    get 'orders_complete' => 'orders#complete'
    get 'orders' => 'orders#index'
  end
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registration: 'admin/registrations'
  }

  get '/admin' => 'admin/homes#top'
  namespace :admin do
    root to:'homes#top'
    resources :genres, only:[:index, :create, :edit, :update]
    resources :items, only:[:new, :create, :index, :show, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end




end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy



end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  attachment :image

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer

  enum payment_method: {credit_card: 0, transfer: 1}
  enum status: {
    waiting: 0,
    paid_up: 1,
    in_production: 2,
    preparing: 3,
    shipped: 4
  }
  def postage
    800
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {
    not_startable: 0,
    awaiting_production: 1,
    in_production: 2,
    production_completed: 3,
  }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to
  end

  def edit
    @genre= Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
 def show
  @order = Order.find(params[:id])
  @order_details = @order.order_details
 end

 def update
  @order = Order.find(params[:id])
  @order_details = @order.order_details
  @order.update(order_params)
  redirect_to admin_order_path
 end

 private
 def order_params
  params.require(:order).permit(:status)
 end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number])
  end



  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="row">
 <h4><div class="admin-title">ジャンル編集</div></h4>
</div>
<div class="row">
 <%= form_with model: @genre, method: :patch, url: admin_genre_path, local: true do |f| %>
 <%= f.label :ジャンル名, class:"mr-5" %>
 <%= f.text_field :name, class:"mr-5" %>
 <%= f.submit "変更を保存", class:"btn btn-success w-120px" %>
 <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="row">
 <h4><div class="admin-title">ジャンル一覧・追加</div></h4>
</div>
<div class="row">
 <%= form_with model: @genre, url:admin_genres_path, local:true do |f| %>
 <%= f.label :ジャンル名, class:"mr-5" %>
 <%= f.text_field :name, placeholder: "ジャンル名", class:"mr-5" %>
 <%= f.submit "新規登録", class: "btn btn-success w-120px" %>
 <% end %>
</div>
<div class="row mt-4">
 <div class="col-4">
 <table class="table table-hover">
  <thead>
   <tr class="table-color">
    <th>ジャンル</th>
    <th></th>
   </tr>
  </thead>
  <tbody>
   <% @genres.each do |genre| %>
   <tr>
    <td><%= genre.name %></td>
    <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-success w-120px" %></td>
   </tr>
  </tbody>
   <% end %>
 </table>
 </div>
</div>

app/views/admin/items/edit.html.erb
<div class="row">
 <h4><div class="admin-title">商品編集</div></h4>
</div>
<div class="row d-flex justify-content-center">
  <%= form_with model:@item,method: :patch, url: admin_item_path, local: true do |f| %>
 <table class="new-form-table">
  <tbody>
   <tr>
    <td><%= f.label :商品画像 %></td>
    <td><%= f.attachment_field :image %></td>
   </tr>
   <tr>
    <td><%= f.label :商品名 %></td>
    <td><%= f.text_field :name %></td>
   </tr>
   <tr>
    <td><%= f.label :商品説明 %></td>
    <td><%= f.text_area :introduction %></td>
   </tr>
   <tr>
    <td><%= f.label :ジャンル %></td>
    <td><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
   </tr>
   <tr>
    <td><%= f.label :税抜価格 %></td>
    <td><%= f.text_field :price %><span>円</span></td>
   </tr>
   <tr>
    <td><%= f.label :販売ステータス %></td>
    <td>
     <%= f.radio_button :is_active, true, checked: true %>
     <%= f.label :is_active, "販売中", value: true %>
     <%= f.radio_button :is_active, false %>
     <%= f.label :is_active, "販売停止中", value: false %>
    </td>
   </tr>
   </tbody>
  </table>
  <div class="row d-flex justify-content-center">
   <%= f.submit :"変更を保存", class: "btn btn-success w-120px mt-3" %>
  </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="row">
 <h4><div class="admin-title-b">商品一覧</div></h4>
 <%= link_to "+", new_admin_item_path, class: "btn btn-lg rounded-circle text-right ml-auto my-3 shadow-lg"%>
</div>
<div class="row">
 <table class="table">
  <thead>
    <tr class="table-color">
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><ins><%= link_to item.name, admin_item_path(item), class:"text-dark" %></ins></td>
      <td><%= item.price %></td>
      <td><%= item.genre.name %></td>
      <td>
       <% if item.is_active == true %>
        <div class="text-success">販売中</div>
       <% else %>
        販売停止中
       <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
 </table>
</div>
<div class="row">
 <%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class="row">
 <h4><div class="admin-title">商品新規登録</div></h4>
</div>

<div class="row d-flex justify-content-center">
 <%= form_with model: @item, method: :post, url: admin_items_path, local:true do |f| %>
 <table class="new-form-table">
  <tbody>
   <tr>
    <td><%= f.label :商品画像 %></td>
    <td><%= f.attachment_field :image %></td>
   </tr>
   <tr>
    <td><%= f.label :商品名 %></td>
    <td><%= f.text_field :name, placeholder: "商品名" %></td>
   </tr>
   <tr>
    <td><%= f.label :商品説明 %></td>
    <td><%= f.text_area :introduction, placeholder: "ここに説明文を記述します" %></td>
   </tr>
   <tr>
    <td><%= f.label :ジャンル %></td>
    <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: '--選択してください--' %></td>
   </tr>
   <tr>
    <td><%= f.label :税抜価格 %></td>
    <td><%= f.text_field :price, placeholder:"1000" %>円</td>
   </tr>
   <tr>
    <td><%= f.label :販売ステータス %></td>
    <td>
     <%= f.radio_button :is_active, true, checked: true %>
     <%= f.label :is_active, "販売中", value: true %>
     <%= f.radio_button :is_active, false %>
     <%= f.label :is_active, "販売停止中", value: false %>
    </td>
   </tr>
   </tbody>
  </table>
  <div class="row d-flex justify-content-center">
  <%= f.submit :"新規登録", class: "btn btn-success w-120px" %>
  </div>
 <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="row">
  <h4><div class="admin-title">商品詳細</div></h4>
</div>
<div class="row">
  <div class="col-4">
    <%= attachment_image_tag @item, :image, :fill, 300, 220, fallback: "no_image.jpg" %>
  </div>
  <div class="col-8">
    <table class="table table-borderless">
      <tbody>
        <tr>
          <td>商品名</td>
          <td><%= @item.name %></td>
        </tr>

         <tr>
          <td>商品説明</td>
          <td><%= @item.introduction %></td>
         </tr>

         <tr>
          <td>ジャンル</td>
          <td><%= @item.genre.name %></td>
         </tr>

         <tr>
          <td>税込価格<br>（税抜価格）</td>
          <td><%= (@item.price * 1.1).floor %>(<%= @item.price %>)円</td>
        </tr>

         <tr>
          <td>販売ステータス</td>
          <td>
           <% if @item.is_active == true %>
           <div class="text-success">販売中</div>
           <% else %>
           販売停止中
           <% end %>
          </td>
         </tr>
      </tbody>
   </table>
  </div>
</div>
<div class="row d-flex justify-content-center">
 <%= link_to "編集する", edit_admin_item_path(@item), class:"btn btn-success w-120px" %>
</div>

app/views/admin/orders/show.html.erb
<div class="row">
  <h5><div class="admin-title-b">注文履歴詳細</div></h5>
</div>
<div class="row">
  <div class="col-7">
    <table class="table table-borderless">
     <tbody>
      <tr>
       <td>購入者</td>
       <td>
        <%= link_to admin_customer_path(@order.customer) do %>
        <ins class="text-dark">
         <%= @order.customer.last_name %>
         <%= @order.customer.first_name %>
        </ins>
        <% end %>
       </td>
      </tr>
      <tr>
       <td>注文日</td>
       <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
      </tr>
      <tr>
       <td>配送先</td>
       <td>
         〒<%= @order.delivery_postal_code %><%= @order.delivery_address %><br>
         <%= @order.delivery_name %>
       </td>
      </tr>
      <tr>
       <td>支払方法</td>
       <td><%= @order.payment_method_i18n %></td>
      </tr>
      <tr>
       <td>注文ステータス</td>
       <td>
        <%= form_with model: @order, method: :patch, url: admin_order_path(@order), local: true do |f| %>
        <%= f.select :status, Order.statuses_i18n.invert, {prompt: false} %>
        <%= f.submit "更新", class:"btn btn-success ml-4 btn-sm" %>
        <% end %>
       </td>
      </tr>
     </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-8">
    <table class="table">
     <thead>
      <tr class="table-color">
       <th>商品名</th>
       <th>単価（税込）</th>
       <th>数量</th>
       <th>小計</th>
       <th>製作ステータス</th>
      </tr>
     </thead>
     <tbody>
     <% @order_details.each do |order_detail| %>
      <tr>
       <td><%= order_detail.item.name %></td>
       <td><%= order_detail.item.with_tax_price %></td>
       <td><%= order_detail.amount %></td>
       <td><%= order_detail.amount * (order_detail.item.with_tax_price) %></td>
       <td>
        <%= form_with model: @order_detail, method: :patch, local: true do |f| %>
         <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert, {prompt: false} %>
         <%= f.submit "更新", class:"btn btn-success btn-sm ml-2" %>
        <% end %>
       </td>
      </tr>
    <% end %>
     </tbody>
    </table>
  </div>
  <div class="col-3">
   <table class="table table-borderless">
     <tbody>
       <tr>
         <td><b>商品合計<b></td>
         <td><%= @order.billing_amount - @order.postage %>円</td>
       </tr>
       <tr>
         <td><b>送料</b></td>
         <td><%= @order.postage %>円</td>
       </tr>
       <tr>
         <td><b>請求金額合計</b></td>
         <td><%= @order.billing_amount %>円</td>
       </tr>
     </tbody>
   </table>
  </div>
</div>