config/routes.rb
Rails.application.routes.draw do
  root to:'public/homes#top'
  get '/about' => 'public/homes#about'

  scope module: :public do
    get 'customers/confirm' => 'customers#confirm'
    get 'customers/my_page' => 'customers#show'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :customers, only:[:update]
    get 'customers/edit' => 'customers#edit'
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :update, :destroy, :create]
    delete 'cart_items_destroy_all' => 'cart_items#destroy_all'

    get 'orders/new' => 'orders#new'
    get 'orders/:id' => 'orders#show'
    post 'orders/confirm' => 'orders#confirm'
    post 'orders' => 'orders#create'
    get 'orders_complete' => 'orders#complete'
    get 'orders' => 'orders#index'
  end
  devise_for :customers, controllers: {
    sessions: 'public/sessions',
    passwords: 'public/passwords',
    registrations: 'public/registrations'
  }

  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registration: 'admin/registrations'
  }

  get '/admin' => 'admin/homes#top'
  namespace :admin do
    root to:'homes#top'
    resources :genres, only:[:index, :create, :edit, :update]
    resources :items, only:[:new, :create, :index, :show, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end




end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy



end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  attachment :image

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :customer

  enum payment_method: {credit_card: 0, transfer: 1}
  enum status: {
    waiting: 0,
    paid_up: 1,
    in_production: 2,
    preparing: 3,
    shipped: 4
  }
  def postage
    800
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: {
    not_startable: 0,
    awaiting_production: 1,
    in_production: 2,
    production_completed: 3,
  }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to
  end

  def edit
    @genre= Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number])
  end



  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<div class="container border border-dark">
  <nav class="navbar navbar-expand-lg navbar-light sticky-top">
   <a class="navbar-brand mt-4" href="/"><span>NaganoCake</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">

     <% if customer_signed_in? %>
      <li><div class="mr-5"><br>ようこそ、<%= current_customer.last_name %>さん！</div></li>
      <li><%= link_to "マイページ", customers_my_page_path, class:'nav-link text-dark btn btn-outline-dark mr-4 mt-4' %></li>
      <li><%= link_to "商品一覧", items_path, class:"nav-link text-dark btn btn-outline-dark mr-4 mt-4" %></li>
      <li><%= link_to "カート", cart_items_path, class:"nav-link text-dark btn btn-outline-dark mr-4 mt-4" %></li>
      <li><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"nav-link text-dark btn btn-outline-dark mr-4 mt-4"  %></li>
     <% elsif admin_signed_in? %>
      <li class="nav-item"><%= link_to "商品一覧", admin_items_path, class:'nav-link text-dark btn btn-outline-dark mr-4 mt-4'%></li>
      <li class="nav-item"><%= link_to "会員一覧", admin_customers_path, class:'nav-link text-dark btn btn-outline-dark mr-4 mt-4' %></li>
      <li class="nav-item"><%= link_to "注文履歴一覧",admin_path, class:'nav-link text-dark btn btn-outline-dark mr-4 mt-4' %></li>
      <li class="nav-item"><%= link_to "ジャンル一覧", admin_genres_path, class:'nav-link text-dark btn btn-outline-dark mr-4 mt-4' %></li>
      <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:'nav-link text-dark btn btn-outline-dark mt-4' %></li>
     <% else %>
      <li class="nav-item"><%= link_to "About", about_path, class:'nav-link text-dark btn btn-outline-dark mr-4 mt-4' %></li>
      <li class="nav-item"><%= link_to "商品一覧", items_path, class:"nav-link text-dark btn btn-outline-dark mr-4 mt-4" %></li>
      <li class="nav-item"><%= link_to "新規登録", new_customer_registration_path, class:'nav-link text-dark btn btn-outline-dark mr-4 mt-4' %></li>
      <li class="nav-item"><%= link_to "ログイン", new_customer_session_path, class:'nav-link text-dark btn btn-outline-dark mr-4 mt-4' %></li>
     <% end %>
      </div>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <main>
      <div class="container my-5">
      <%= yield %>
      </div>
    </main>
  </body>
</html>